use entrypoint and env vars
vierbergenlars/bareos_exporter pull request #15
Opened 2022-04-03 09:16 UTC by barcus

* add entrypoint script to manage exporter args
* freeeze golang and busybox images version
* add WAIT_FOR_DB variable
* use upx to compress exporter executable

2022-04-03 09:19 UTC, barcus commented
Hello @vierbergenlars, thank you for this nice exporter :)
A sent a small MR to ease usage of your docker image using environment variables.
CMD can be override using a dedicated command in docker run or docker-compose file.
I would like to add this exporter in my docker-compose file (https://github.com/barcus/bareos)

2022-04-03 19:16 UTC, vierbergenlars requested changes
Hi, thanks for your PR to make the docker image more usable.

I have one blocking remark: the backwards compatibility of the Docker image must be retained, as it is used in production.

My other documentation remarks are more suggestions on how to improve the docs.

2022-04-03 19:16 UTC, vierbergenlars commented on Dockerfile
> +CMD ["./bareos_exporter"]
To keep backwards compatibility in the docker image, I think you'll need to set
`ENTRYPOINT ["/entrypoint.sh", "./bareos_exporter"]`

Otherwise, the parameters passed to docker run will replace the bareos_exporter CMD.

2022-04-03 19:16 UTC, vierbergenlars commented on README.md
> +Using default variables (expected DB_PASSWORD)
Default variables or custom variables are the same, except for some variable names set.

Can you drop this section and only keep the custom variables?

2022-04-03 19:16 UTC, vierbergenlars commented on README.md
> +Using custom variables
```suggestion
### Using environment variables
```

2022-04-03 19:16 UTC, vierbergenlars commented on README.md
> +Using custom Docker CMD
```suggestion
### Using Docker CMD options
```

2022-04-03 19:16 UTC, vierbergenlars commented on README.md
> +docker run --name bareos_exporter -p 9625:9625 -d vierbergenlars/bareos_exporter:latest ./bareos_exporter -dsn 'mysql://login:password@tcp(host:port)/dbname?parseTime=true'
For backwards compatibility of the docker image, it needs to work like this.

```suggestion
docker run --name bareos_exporter -p 9625:9625 -d vierbergenlars/bareos_exporter:latest -dsn 'mysql://login:password@tcp(host:port)/dbname?parseTime=true'
```

2022-04-03 19:16 UTC, vierbergenlars commented on README.md
> +### Default variables
This belongs in the "using environment variables" section.

2022-04-03 19:16 UTC, vierbergenlars commented on README.md
> +* `WAIT_FOR_DB` 0
The "PORT" variable is not documented.

2022-04-03 22:00 UTC, barcus commented on Dockerfile
> +CMD ["./bareos_exporter"]
Don't like it so much. I fixed it in entrypoint. Let me know if it looks good to you. I tested it for your case for sure.
Only bad point is that CMD can not be used to override default command simply. Should work using entrypoint options. like `docker run --entrypoint=/bin/sh vierbergenlars/bareos_exporter`

2022-04-04 06:47 UTC, vierbergenlars approved these changes
Thanks, looks good now!

2022-04-04 06:47 UTC, merged